# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Errorlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(default='', max_length=100)),
                ('ip', models.CharField(default='', max_length=20)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('S', 'Success'), ('F', 'Failure'), ('U', 'Unknown')], default='U', max_length=10)),
                ('chat_id', models.IntegerField(default=0)),
                ('tr_type', models.CharField(choices=[('D', 'On Demand'), ('A', 'Automatic')], default='A', max_length=10)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Server')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.AddField(
            model_name='errorlog',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Transaction'),
        ),
    ]
