# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='response',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='transaction',
            name='text',
            field=models.CharField(default='', max_length=100),
        ),
    ]
